[profile.release]
lto = true
opt-level = 3

[workspace]
members = [
    "tranquility",
    "tranquility-content-length-limit",
    "tranquility-http-signatures",
    "tranquility-ratelimit",
    "tranquility-types",
]
