# The email and jaeger configuration parts are always required, regardless of the enabled features
#
# The mail server has to support TLS, either via regular TLS or STARTTLS
# Using an unencrypted transport is not supported and should not even be used anywhere anymore
[email]
# Activate/Deactivate email functionality
active = false
# Domain of the mail server
server = "smtp.example.com"
# Whether STARTTLS should be used or not
starttls = false
# Email address of the mail account
email = "noreply@example.com"
# Username of the mail account
username = "tranquility"
# Password of the mail account
password = "verysecurepassword"

[instance]
# Maximum limit of characters per post
character-limit = 1024
# If set to "true", the instance won't allow new users to sign up and always return a "403 Forbidden" status code
# Useful for private/single user instances or instances with a large spam account problem
closed-registrations = false
# This is the description of your instance
# It is delivered via the instance information endpoint (/api/v1/instance) as well as via nodeinfo
description = """
An ActivityPub instance running Tranquility
"""
# This is a very important value
# Change this to your domain (eg. fedi.my-cool-domain.com) before you start Tranquility for the first time
# This value is used to create the URLs used in activities
# If it is set to a wrong domain, federation will break! 
# 
# !! ActivityPub entities will not automatically update when this value changes !!
# !! You'll either have to change every activity manually or start from scratch (the latter option is by far easier) !!
domain = "tranquility.example.com"
# Moderators of your instance
# The moderators have the rights to delete any post from the instance
# Specify them by adding their username to the list below
moderators = [ ]
# Upload limit for profile/header pictures, attachments, etc. in kilobytes
# Defaults to 2048 (2MB)
upload-limit = 2048

[jaeger]
# Host of the jaeger collector
host = "localhost"
# Port of the collector accepting the compact thrift protocol
port = 6831

[ratelimit]
# Activates ratelimiting for routes responsible for authentication and for the registration endpoint
active = true
# Those values are quotas per hour respectively
authentication-quota = 50
registration-quota = 10

[server]
interface = "127.0.0.1"
port = 8080
database-url = "postgres://localhost/tranquility"

[tls]
# Tranquility doesn't necessarily need a reverse proxy like NGINX for TLS support
# If this option is set to "true", Tranquility will use the files set below
# as the TLS certificate/key to communicate via TLS over the previously specified port
# 
# If you need a TLS certificate, get one for free from an authority like Let's Encrypt (https://letsencrypt.org)
# 
# !! Setting this to "false" and running Tranquility without any kind of reverse proxy will probably not work !!
# !! Please use a free certificate authority like the aforementioned Let's Encrypt !!
serve-tls-directly = false

certificate = "tranquility.crt"
secret-key = "tranquility.key"
