[package]
name = "tranquility-types"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
chrono = { version = "0.4.19", optional = true }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"

[features]
activitypub = ["chrono"]
mastodon = [ ]
nodeinfo = [ ]
webfinger = [ ]
