[package]
name = "tranquility-ratelimit"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
governor = "0.4.2"
thiserror = "1.0.30"

[dependencies.warp]
version = "0.3.2"
default-features = false
