[package]
name = "tranquility-ratelimit"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
axum = { version = "0.5.2", default-features = false }
futures-util = "0.3.21"
governor = "0.4.2"
thiserror = "1.0.30"
tower-layer = "0.3.1"
tower-service = "0.3.1"
tracing = "0.1.34"

[features]
