[package]
name = "tranquility"
version = "0.1.0"
authors = ["Glitch <smallglitch@cryptolab.net>"]
edition = "2018"
license = "MIT"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ammonia = "3"
askama = "0.10"
async-trait = "0.1"
base64 = "0.13"
cached = "0.23"
chrono = "0.4"
clap = "3.0.0-beta.2"
futures-util = "0.3"
hex = "0.4"
itertools = "0.10"
once_cell = "1"
rand = "0.7"
rayon = "1"
regex = "1"
rust-argon2 = "0.8"
serde_json = "1"
sha2 = "0.9"
thiserror = "1"
tokio-compat-02 = "0.2"
tracing = "0.1"
tracing-subscriber = "0.2"
url = "2"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = [
    "json",
    "rustls",
]

[dependencies.rsa]
git = "https://github.com/RustCrypto/RSA.git"
rev = "a9c5797877a94fd48a1654bdb6b72717d71f5952"

[dependencies.serde]
version = "1.0"
default-features = false
features = [
    "derive",
]

[dependencies.sqlx]
version = "0.4"
default-features = false
features = [
    "chrono",
    "json",
    "macros",
    "migrate",
    "offline",
    "postgres",
    "runtime-tokio-rustls",
    "uuid",
]

[dependencies.tokio]
version = "1"
features = [
    "full",
    "tracing"
]

[dependencies.tranquility-http-signatures]
path = "../tranquility-http-signatures"
features = [ "reqwest" ]

[dependencies.tranquility-ratelimit]
path = "../tranquility-ratelimit"

[dependencies.tranquility-types]
path = "../tranquility-types"

[dependencies.uuid]
version = "0.8"
features = [
    "serde",
    "v4",
]

[dependencies.validator]
version = "0.12"
features = [
    "derive",
]

[dependencies.warp]
version = "0.3"
features = [
    "compression",
    "tls",
]

[features]
default = [ ]
