[package]
name = "tranquility"
version = "0.1.0"
authors = ["Glitch <smallglitch@cryptolab.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-argon2 = "0.8"
chrono = "0.4"
clap = "3.0.0-beta.2"
futures-util = "0.3"
log = "0.4"
once_cell = "1.4"
pretty_env_logger = "0.4"
rand = "0.7"
regex = "1.3"
reqwest = { version = "0.10", default-features = false, features = [ "json", "rustls-tls" ] }
rsa = { git = "https://github.com/RustCrypto/RSA.git", rev = "c879eb2", features = [ "pem" ] }
serde = { version = "1.0", default-features = false, features = [ "derive" ] }
serde_json = "1.0"
sqlx = { version = "0.4.0-beta.1", default-features = false, features = [ "chrono", "json", "macros", "migrate", "offline", "postgres", "runtime-tokio", "uuid" ] }
thiserror = "1.0"
tokio = { version = "0.2", features = [ "full" ] }
tranquility-types = { path = "../tranquility-types" }
uuid = "0.8"
warp = { version = "0.2", features = [ "compression", "tls" ] }

# Needed because of sqlx-rt which depends on "native-tls" (required OpenSSL dev libraries on Linux)
# The vendored feature is activated for portability reasons
[target.'cfg(target_os = "linux")'.dependencies]
openssl-sys = { version = "0.9", features = [ "vendored" ] }
