on:
  schedule:
    - cron: '0 1 * * *'

name: Nightly build

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (Linux x86)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - shell: bash
        run: mv target/release/tranquility target/release/tranquility-x86

      - uses: actions/upload-artifact@v2
        with:
          name: tranquility-linux
          path: target/release/tranquility-x86
          retention-days: 1
    
  build_armv7:
    name: Build (Linux ARMv7)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target armv7-unknown-linux-gnueabihf

      - shell: bash
        run: mv target/armv7-unknown-linux-gnueabihf/release/tranquility target/armv7-unknown-linux-gnueabihf/release/tranquility-armv7

      - uses: actions/upload-artifact@v2
        with:
          name: tranquility-linux-armv7
          path: target/armv7-unknown-linux-gnueabihf/release/tranquility-armv7
          retention-days: 1

  publish:
    needs: [build, build_armv7]
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete_release: true
          tag_name: nightly
      
      - uses: actions/download-artifact@v2

      - name: Upload binaries
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          prerelease: true
          files: >
            tranquility-linux-x86:./tranquility-linux/tranquility-x86
            tranquility-linux-armv7:./tranquility-linux-armv7/tranquility-armv7
